# Generated by Django 4.2.7 on 2023-12-01 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_off', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('rub', 'rubles'), ('usd', 'dollars')], max_length=10)),
                ('duration', models.CharField(choices=[('forever', 'forever'), ('once', 'once'), ('repeating', 'repeating')], max_length=10)),
                ('duration_in_months', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['amount_off'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='item.coupon'),
            preserve_default=False,
        ),
    ]
