# Generated by Django 4.2.7 on 2023-12-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_coupon_remove_order_discount_delete_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='currency',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='duration',
            field=models.CharField(choices=[('f', 'forever'), ('o', 'once'), ('r', 'repeating')], max_length=10),
        ),
    ]
