# Generated by Django 4.2.7 on 2023-12-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_coupon_currency_alter_coupon_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='duration_in_months',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
