# Generated by Django 4.2.7 on 2023-11-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_itemorder_order_itemorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default=2, max_length=3),
            preserve_default=False,
        ),
    ]
