# Generated by Django 4.2.7 on 2023-12-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_coupon_duration_in_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='duration_in_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
