# Generated by Django 4.2.7 on 2023-12-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_coupon_duration_in_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='duration',
            field=models.CharField(choices=[('forever', 'forever'), ('once', 'once'), ('repeating', 'repeating')], max_length=10),
        ),
    ]
