# Generated by Django 4.2.7 on 2023-11-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_itemorder_options_alter_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('r', 'rub'), ('d', 'dol')], max_length=3),
        ),
    ]
