# Generated by Django 4.2.7 on 2023-11-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rubles', 'rub'), ('dollars', 'usd')], max_length=10),
        ),
    ]
